language: node_js
node_js: 12

addons:
  sonarcloud:
    organization: "naasse"

cache:
  directories:
    - node_modules

before_install:
  - npm update

install:
  - npm install

script:
  - npm run lint
  - npm run test:coverage
  - sonar-scanner
  - npm run predeploy

deploy:
  provider: pages
  local_dir: build
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
